// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9DXnX6YSjjwBQW90jjaGZsffCFXbktcU',
    appId: '1:1004878179078:web:dd78b76c736b7daad8cc87',
    messagingSenderId: '1004878179078',
    projectId: 'senior-project-662d8',
    authDomain: 'senior-project-662d8.firebaseapp.com',
    storageBucket: 'senior-project-662d8.appspot.com',
    measurementId: 'G-1H0DVBWEVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GKqm5yIkQMajnLhksHL5cya3b4Hvsu0',
    appId: '1:1004878179078:android:648b7e11cd20059fd8cc87',
    messagingSenderId: '1004878179078',
    projectId: 'senior-project-662d8',
    storageBucket: 'senior-project-662d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz3bYgWIkv6nmJ0OjI_XpUxSXBCDjrozk',
    appId: '1:1004878179078:ios:fe2910c72a92aab6d8cc87',
    messagingSenderId: '1004878179078',
    projectId: 'senior-project-662d8',
    storageBucket: 'senior-project-662d8.appspot.com',
    iosBundleId: 'com.example.seniorproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz3bYgWIkv6nmJ0OjI_XpUxSXBCDjrozk',
    appId: '1:1004878179078:ios:fe2910c72a92aab6d8cc87',
    messagingSenderId: '1004878179078',
    projectId: 'senior-project-662d8',
    storageBucket: 'senior-project-662d8.appspot.com',
    iosBundleId: 'com.example.seniorproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9DXnX6YSjjwBQW90jjaGZsffCFXbktcU',
    appId: '1:1004878179078:web:f4ed77a80d67567dd8cc87',
    messagingSenderId: '1004878179078',
    projectId: 'senior-project-662d8',
    authDomain: 'senior-project-662d8.firebaseapp.com',
    storageBucket: 'senior-project-662d8.appspot.com',
    measurementId: 'G-R7FK1ZNEX3',
  );
}
